### ISSUE TITLE
[FEATURE] Add manual angle adjustment for gliding control

### ISSUE THREAD

**Issue by Happyrobot33** [Mattshark89/OpenFlight-VRC#58]
Add the ability to control what angle means *forwards* relative to your controllers

**Comment by Happyrobot33** [comment]
Might also adjust the actual default angle just to account for other controllers

**Comment by Salireths** [comment]
I have been experiencing issues with wings not aligning how they intuitively would work. I use Quest2 controllers (with Standable), and to glide forward I have to hold my wings vertically, like I'm breaking in the air/about to land, instead of holding them flat horizontally. To fly up I have to twist my wing completely unnaturally. Sadly It is both uncomfortable and not immersive, it's like there is 90 degrees offset almost. 
- Having some way to adjust rotational offset (even if it's a manual per-world VRCX-saved setting) would make it actually properly usable.
- Additionally it would be very beneficial to have an option to draw debug visualization of how the Open Flight expects your wings to be rotated and sized (like a transparent wing, or just a plane).

I'm available to contact for additional feedback and testing! Discord/Telegram is **Salireths**

**Comment by Happyrobot33** [comment]
Added and confirmed functional in latest beta
